### ISSUE TITLE
Please consider renaming

### ISSUE THREAD

**Issue by zenspider** [PeterCamilleri/minitest_visible#1]
Following the standard here: http://guides.rubygems.org/name-your-gem/

Also, please send me a PR with your gem listed in my "known extensions" list.

**Comment by PeterCamilleri** [comment]
I'm not certain as to what action to take. To be honest, I thought I was following the guide you reference. I'm not sure where I went wrong. This gem was created in an effort to dry up my test code. The only change I can see is changing the name to minitest-visible, but that would imply require 'minitest/visible' which won't work as visible is not an actual part of minitest. Is it the "visible" that needs to be changed?

**Comment by PeterCamilleri** [comment]
No reply. Closing.
